/home/joao/programs/galfit/galfit ./1502/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2587/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2654/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./1056/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./706/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./107/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./590/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2469/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2414/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./1601/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2465/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./229/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./916/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./795/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3022/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3544/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./1074/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./927/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./643/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4067/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4685/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./487/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./1963/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./394/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4843/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4867/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2516/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3586/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4316/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4967/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./2100/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4122/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./30/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./66/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./839/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3907/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3774/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./4636/galfit_sph.feedme 
/home/joao/programs/galfit/galfit ./3162/galfit_sph.feedme 
