python3 fit_lens_light_galfit.py 1502
galfit galfit.feedme ./galfit_lens_light_subtraction/1502/galfit.feedme 
python3 fit_lens_light_galfit.py 2587
galfit galfit.feedme ./galfit_lens_light_subtraction/2587/galfit.feedme 
python3 fit_lens_light_galfit.py 2654
galfit galfit.feedme ./galfit_lens_light_subtraction/2654/galfit.feedme 
python3 fit_lens_light_galfit.py 1056
galfit galfit.feedme ./galfit_lens_light_subtraction/1056/galfit.feedme 
python3 fit_lens_light_galfit.py 706
galfit galfit.feedme ./galfit_lens_light_subtraction/706/galfit.feedme 
python3 fit_lens_light_galfit.py 107
galfit galfit.feedme ./galfit_lens_light_subtraction/107/galfit.feedme 
python3 fit_lens_light_galfit.py 590
galfit galfit.feedme ./galfit_lens_light_subtraction/590/galfit.feedme 
python3 fit_lens_light_galfit.py 2469
galfit galfit.feedme ./galfit_lens_light_subtraction/2469/galfit.feedme 
python3 fit_lens_light_galfit.py 2414
galfit galfit.feedme ./galfit_lens_light_subtraction/2414/galfit.feedme 
python3 fit_lens_light_galfit.py 1601
galfit galfit.feedme ./galfit_lens_light_subtraction/1601/galfit.feedme 
python3 fit_lens_light_galfit.py 2465
galfit galfit.feedme ./galfit_lens_light_subtraction/2465/galfit.feedme 
python3 fit_lens_light_galfit.py 229
galfit galfit.feedme ./galfit_lens_light_subtraction/229/galfit.feedme 
python3 fit_lens_light_galfit.py 916
galfit galfit.feedme ./galfit_lens_light_subtraction/916/galfit.feedme 
python3 fit_lens_light_galfit.py 795
galfit galfit.feedme ./galfit_lens_light_subtraction/795/galfit.feedme 
python3 fit_lens_light_galfit.py 3022
galfit galfit.feedme ./galfit_lens_light_subtraction/3022/galfit.feedme 
python3 fit_lens_light_galfit.py 3544
galfit galfit.feedme ./galfit_lens_light_subtraction/3544/galfit.feedme 
python3 fit_lens_light_galfit.py 1074
galfit galfit.feedme ./galfit_lens_light_subtraction/1074/galfit.feedme 
python3 fit_lens_light_galfit.py 3352
galfit galfit.feedme ./galfit_lens_light_subtraction/3352/galfit.feedme 
python3 fit_lens_light_galfit.py 1745
galfit galfit.feedme ./galfit_lens_light_subtraction/1745/galfit.feedme 
python3 fit_lens_light_galfit.py 1085
galfit galfit.feedme ./galfit_lens_light_subtraction/1085/galfit.feedme 
python3 fit_lens_light_galfit.py 927
galfit galfit.feedme ./galfit_lens_light_subtraction/927/galfit.feedme 
python3 fit_lens_light_galfit.py 3050
galfit galfit.feedme ./galfit_lens_light_subtraction/3050/galfit.feedme 
python3 fit_lens_light_galfit.py 1118
galfit galfit.feedme ./galfit_lens_light_subtraction/1118/galfit.feedme 
python3 fit_lens_light_galfit.py 643
galfit galfit.feedme ./galfit_lens_light_subtraction/643/galfit.feedme 
python3 fit_lens_light_galfit.py 4768
galfit galfit.feedme ./galfit_lens_light_subtraction/4768/galfit.feedme 
python3 fit_lens_light_galfit.py 502
galfit galfit.feedme ./galfit_lens_light_subtraction/502/galfit.feedme 
python3 fit_lens_light_galfit.py 4067
galfit galfit.feedme ./galfit_lens_light_subtraction/4067/galfit.feedme 
python3 fit_lens_light_galfit.py 334
galfit galfit.feedme ./galfit_lens_light_subtraction/334/galfit.feedme 
python3 fit_lens_light_galfit.py 4685
galfit galfit.feedme ./galfit_lens_light_subtraction/4685/galfit.feedme 
python3 fit_lens_light_galfit.py 487
galfit galfit.feedme ./galfit_lens_light_subtraction/487/galfit.feedme 
python3 fit_lens_light_galfit.py 1963
galfit galfit.feedme ./galfit_lens_light_subtraction/1963/galfit.feedme 
python3 fit_lens_light_galfit.py 394
galfit galfit.feedme ./galfit_lens_light_subtraction/394/galfit.feedme 
python3 fit_lens_light_galfit.py 4843
galfit galfit.feedme ./galfit_lens_light_subtraction/4843/galfit.feedme 
python3 fit_lens_light_galfit.py 4867
galfit galfit.feedme ./galfit_lens_light_subtraction/4867/galfit.feedme 
python3 fit_lens_light_galfit.py 1756
galfit galfit.feedme ./galfit_lens_light_subtraction/1756/galfit.feedme 
python3 fit_lens_light_galfit.py 2516
galfit galfit.feedme ./galfit_lens_light_subtraction/2516/galfit.feedme 
python3 fit_lens_light_galfit.py 3586
galfit galfit.feedme ./galfit_lens_light_subtraction/3586/galfit.feedme 
python3 fit_lens_light_galfit.py 4316
galfit galfit.feedme ./galfit_lens_light_subtraction/4316/galfit.feedme 
python3 fit_lens_light_galfit.py 4967
galfit galfit.feedme ./galfit_lens_light_subtraction/4967/galfit.feedme 
python3 fit_lens_light_galfit.py 2100
galfit galfit.feedme ./galfit_lens_light_subtraction/2100/galfit.feedme 
python3 fit_lens_light_galfit.py 3600
galfit galfit.feedme ./galfit_lens_light_subtraction/3600/galfit.feedme 
python3 fit_lens_light_galfit.py 4122
galfit galfit.feedme ./galfit_lens_light_subtraction/4122/galfit.feedme 
python3 fit_lens_light_galfit.py 30
galfit galfit.feedme ./galfit_lens_light_subtraction/30/galfit.feedme 
python3 fit_lens_light_galfit.py 66
galfit galfit.feedme ./galfit_lens_light_subtraction/66/galfit.feedme 
python3 fit_lens_light_galfit.py 839
galfit galfit.feedme ./galfit_lens_light_subtraction/839/galfit.feedme 
python3 fit_lens_light_galfit.py 3907
galfit galfit.feedme ./galfit_lens_light_subtraction/3907/galfit.feedme 
python3 fit_lens_light_galfit.py 3774
galfit galfit.feedme ./galfit_lens_light_subtraction/3774/galfit.feedme 
python3 fit_lens_light_galfit.py 4636
galfit galfit.feedme ./galfit_lens_light_subtraction/4636/galfit.feedme 
python3 fit_lens_light_galfit.py 3162
galfit galfit.feedme ./galfit_lens_light_subtraction/3162/galfit.feedme 
python3 fit_lens_light_galfit.py 2660
galfit galfit.feedme ./galfit_lens_light_subtraction/2660/galfit.feedme 
